# Generated by Django 4.2 on 2024-09-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login",
                    models.CharField(max_length=255, unique=True, verbose_name="Логин"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Пароль")),
            ],
            options={
                "verbose_name": "Логин",
                "verbose_name_plural": "Логины",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=100, verbose_name="Тема")),
                ("send_date", models.DateTimeField(verbose_name="Дата отправки")),
                ("receipt_date", models.DateTimeField(verbose_name="Дата получения")),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                ("attachments_list", models.TextField(verbose_name="Список вложений")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="post_messages.login",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("-send_date",),
            },
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("owner", "send_date", "theme"), name="unique_message"
            ),
        ),
    ]
