# Generated by Django 4.2 on 2024-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="theme",
            field=models.CharField(max_length=200, verbose_name="Тема"),
        ),
    ]
