# Generated by Django 4.2 on 2024-09-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_messages", "0004_alter_message_attachments_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachments_list",
            field=models.TextField(
                default="Без вложений", verbose_name="Список вложений"
            ),
        ),
    ]
